### ISSUE TITLE
Testing GV Reimagined

### ISSUE THREAD

**Issue by phillipwilhelm** [gravityview/GravityView-Reimagined#1]
Any notes on how to try installing/testing this?

I've installed on WP 4.5 and enabled/disabled the GravityView plugin where I have a license with you guys, but the WP-Admin area shows a white screen. 

Thoughts? I'd love to give some feedback and play around with this.

**Comment by zackkatz** [comment]
Thanks for your interest!

I've [updated the readme](https://github.com/gravityview/GravityView-Reimagined) to have basic usage information. Keep GravityView active while using this plugin as well (for now).

Here's another one I didn't include:

```
// First, navigate to a View CPT or a page with a [gravityview] shortcode.

/** @var \GV\View $view */
while ( gravityview()->views->has_views() ) {

	gravityview()->views->current()->render();

	gravityview()->views->next();
}
```

**Comment by zackkatz** [comment]
Please feel free to ask questions as issues. I'm also very open to feedback.

**Comment by phillipwilhelm** [comment]
For some reason I had tried this and it ended up giving me a white screen.... I am running 4.5 which could be the reason.
